# https://taskfile.dev
version: 3

vars:
  dir: ./bin/
  app_name_windows: goto.exe
  app_name_linux: goto
  main_file: ./cmd/goto/main.go

tasks:
  default:
    desc: Default task which will be run if no target is specified
    aliases:
      - all
    cmds:
      - task: clean
      - task: setup
      - task: tidy
      - task: mod
      - task: test
      - task: build

  setup:
    cmds:
      - cmd: mkdir {{.dir}}
        platforms: [darwin, linux]
      - cmd: powershell mkdir {{.dir}}
        platforms: [ windows ]

  build:
    deps: [clean]
    cmds:
      - cmd: go build -v -o {{.dir}}{{.app_name_windows}} {{.main_file}}
        platforms: [windows]
      - cmd: go build -v -o {{.dir}}{{.app_name_linux}} {{.main_file}}
        platforms: [darwin, linux]
  test:
    cmds:
      - go test -v ./...

  tidy:
    cmds:
      - go mod tidy

  mod:
    cmds:
      - go mod download

  clean:
    cmds:
      - cmd: rm -rf {{.dir}}*
        platforms: [darwin, linux]
      - cmd: powershell rm {{.dir}}* && powershell Remove-Item {{.dir}} -Force
        platforms: [windows]
